/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package whatstrack
import com.fasterxml.jackson.databind.ObjectMapper
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import com.google.gson.Gson
import com.google.gson.GsonBuilder
data class MyLanguage (
    val code:String
)
data class MyTemplate (
    val name:String,
    val language:MyLanguage
)
data class RequestBody (
    val messaging_product:String,
    val to:String,
    val type:String,
    val template:MyTemplate
)
data class TextMessageContent (
      val preview_url:Boolean,
    val body:String
)
data class TextMessageObject (
      val messaging_product:String,
    val recipient_type:String,
    val to:String,
    val type:String,
    val text:TextMessageContent 
)
data class ReactionObject (
    val message_id:String,
    val emoji:String
)
data class ImageObject (
    val link:String
)
data class ReactionMessageObject (
    val messaging_product:String,
    val recipient_type:String,
    val to:String,
    val type:String,
    val reaction:ReactionObject
)
data class ImageMessageObject (
    val messaging_product:String,
    val recipient_type:String,
    val to:String,
    val type:String,
    val image:ImageObject
)

data class LocationObject (
    val longitude:String,
    val latitude:String,
    val name:String,
    val address:String
)
data class LocationMessageObject (
      val messaging_product:String,
      val to:String,
      val type:String,
      val location:LocationObject 

)
data class ButtonReply (
    val id:String,
    val title:String
)
data class ButtonRow (
    val type:String,
    val reply:ButtonReply
)
data class InteractiveAction(
    val buttons:listOf ()<ButtonRow>
)
data class InteractiveBody (
    val text:String
)
data class InteractiveObject (
    val type:String,
    val body:InteractiveBody,
    val action:InteractiveAction
)
data class InteractiveButtonMessageObject (
       val messaging_product:String,
    val recipient_type:String,
    val to:String,
    val type:String,
    val interactive:InteractiveObject
)

data class 
class App {
fun sendRequestToFacebook (requestBodyString:String){
      val client = HttpClient.newBuilder().build();
    val request = HttpRequest.newBuilder()
        .uri(URI.create("https://graph.facebook.com/v15.0/103161752650905/messages"))
        .POST(HttpRequest.BodyPublishers.ofString(requestBodyString))
         .header("Content-Type", "application/json")
         .header ("Authorization","Bearer EAAJF5XMdhTIBAEKrLVb4RHyIp6qOiiZB05A4AgIhpfD2WgG8SPbItGE0O0Xfmkk2hsPaCjAV03NIdw2dxZCtpFl7lZALgUv7AIZAJOZCpP8TwVZAj8Py5OKsZCzY0K1LIJEHIB37kl5TNYcXcL43Mxx34PO7wZBQqAfaUGo4wjxtbBhekPQomvyFSLILoOxi1TNJlIUgPTXepwZDZD")
        .build()
    val response = client.send(request, HttpResponse.BodyHandlers.ofString());
    println(response.body())
}
fun sendImage (){
    val imageMessageObject = ImageMessageObject (
        "whatsapp",
        "individual",
        "919820011185",
        "type": "image",
        ImageObject (
            "https://images.pling.com/img/00/00/48/70/84/1220648/e4fff450a6306e045f5c26801ce31c3efaeb.jpg"
        )
    )
    val gson = Gson()
    val imageMessageString:String = gson.toJson (imageMessageString) 
    println (imageMessageString)
    sendRequestToFacebook (imageMessageString)
    

}
fun sendReactionMessage (){
    val reactionMessageObject = ReactionMessageObject (
        "whatsapp",
        "individual",
        "919820011185",
        "reaction",
        ReactionObject (
            "test",
            "\uD83D\uDE00"
        )
    )

}
fun sendTextMessage (){
val textMessageObject = TextMessageObject (
    "whatsapp",

    "individual",
    "919820011185",
    "text",
    TextMessageContent (
        false,
        "Hello World"
    )
)
 val gson = Gson()
 val textMessageString:String = gson.toJson (textMessageObject) 
 println (textMessageString)
 sendRequestToFacebook (textMessageString)
}
fun sendTemplateMessage (){
    val myLanguage = MyLanguage ("en_US")
    val myTemplate = MyTemplate ("hello_world",myLanguage)
    val gson = Gson()
    val requestBody = RequestBody ("whatsapp","919820011185","template",myTemplate)

	val requestBodyString: String = gson.toJson(requestBody)
    println (requestBodyString)
    // val requestBody: String = "{ \"messaging_product\": \"whatsapp\", \"to\": \"919820011185\", \"type\": \"template\", \"template\": { \"name\": \"hello_world\", \"language\": { \"code\": \"en_US\" } } }"
    sendRequestToFacebook (requestBodyString)
}
}

fun main() {
    // println(App().sendTemplateMessage())
    println(App().sendTextMessage())
}
